name: pull request

on:
  pull_request:
    paths:
      - 'source/DefaultEcs/**'
      - 'source/DefaultEcs.Test/**'

jobs:
  pull_request:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Run tests net462
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f net462 /p:TEST=true

    - name: Run tests net48
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f net48 /p:TEST=true

    - name: Run tests net7.0
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f net6.0 /p:TEST=true